# Generated by Django 5.2.6 on 2025-09-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=20)),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("year", models.PositiveSmallIntegerField()),
                ("roof_type", models.CharField(max_length=100)),
                ("fuel_type", models.CharField(max_length=100)),
            ],
        ),
    ]
