# Generated by Django 5.2.6 on 2025-09-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("select_one", "Select One"),
                    ("gas", "Gas"),
                    ("diesel", "Diesel"),
                    ("hybrid", "Hybrid"),
                    ("lp_gas", "LP Gas"),
                ],
                default="Select One",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="roof_type",
            field=models.CharField(
                choices=[
                    ("select_one", "Select One"),
                    ("solid", "Solid"),
                    ("sun_roof", "Sun Roof"),
                    ("convertable", "Convertable"),
                ],
                default="Select One",
            ),
        ),
    ]
