# Generated by Django 5.2.6 on 2025-09-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0002_alter_car_fuel_type_alter_car_roof_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("source ", "Select One"),
                    ("gas", "Gas"),
                    ("diesel", "Diesel"),
                    ("hybrid", "Hybrid"),
                    ("lp_gas", "LP Gas"),
                ],
                default="Select One",
            ),
        ),
    ]
